import React, { useState } from 'react';
import { CreditCard, Check, ShieldCheck, Plus, Trash2, Clock, AlertCircle } from 'lucide-react';

export interface AuditLog {
  id: string;
  timestamp: string;
  event: string;
  details: string;
  type: 'success' | 'info' | 'warn';
}

interface PaymentStatusSectionProps {
  cardDigits: string;
  setCardDigits: (digits: string) => void;
  cardExpiry: string;
  setCardExpiry: (exp: string) => void;
  cardCvv: string;
  setCardCvv: (cvv: string) => void;
  auditLogs: AuditLog[];
  onLogMessage: (text: string, type: 'info' | 'success' | 'warn') => void;
}

export function PaymentStatusSection({
  cardDigits,
  setCardDigits,
  cardExpiry,
  setCardExpiry,
  cardCvv,
  setCardCvv,
  auditLogs,
  onLogMessage
}: PaymentStatusSectionProps) {
  const [showAddCardModal, setShowAddCardModal] = useState(false);
  
  // Local card state
  const [inputDigits, setInputDigits] = useState('4532 7182 9381 2309');
  const [inputExpiry, setInputExpiry] = useState('12/28');
  const [inputCvv, setInputCvv] = useState('***');

  const handleSwapCard = (e: React.FormEvent) => {
    e.preventDefault();

    const cleanDigits = inputDigits.trim();
    if (cleanDigits.length < 15) {
      onLogMessage("Card number appears too short. Please type a valid credit card format.", "warn");
      return;
    }

    setCardDigits(cleanDigits);
    setCardExpiry(inputExpiry);
    setCardCvv(inputCvv);
    setShowAddCardModal(false);
    onLogMessage(`Payment source credentials swapped successfully. Card Ending: ${cleanDigits.slice(-4)}.`, "success");
  };

  return (
    <div id="payment_status_section" className="grid grid-cols-1 md:grid-cols-2 gap-6">
      
      {/* Visual Credit Card */}
      <div className="p-6 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl shadow-xs flex flex-col justify-between space-y-6">
        <div>
          <div className="flex justify-between items-center">
            <h3 className="text-xs font-mono font-bold text-slate-400 uppercase tracking-wider">Payment Method</h3>
            <span className="px-2 py-0.5 text-[10px] font-mono font-bold bg-blue-100 dark:bg-blue-950 text-blue-600 dark:text-blue-400 rounded">
              Primary
            </span>
          </div>
          
          {/* Card Graphic */}
          <div className="mt-5 p-5 bg-gradient-to-tr from-slate-950 to-blue-900 rounded-xl relative overflow-hidden text-white shadow-md select-none border border-zinc-800">
            <div className="absolute right-0 bottom-0 top-0 w-1/2 bg-blue-500/10 rounded-l-full blur-xl pointer-events-none" />
            <div className="flex justify-between items-start">
              <span className="text-[10px] font-mono font-bold tracking-widest text-zinc-350">SALESPILOT ENTERPRISE</span>
              <span className="font-mono italic font-bold text-base text-zinc-200">Visa</span>
            </div>

            <div className="mt-8">
              <span className="block text-sm font-mono tracking-widest text-zinc-100">{cardDigits}</span>
            </div>

            <div className="mt-6 flex justify-between items-center">
              <div>
                <span className="block text-[8px] text-zinc-455 font-mono uppercase tracking-widest">Card Holder</span>
                <span className="text-[10px] font-mono font-bold">Horizon Media Group</span>
              </div>
              <div className="text-right">
                <span className="block text-[8px] text-zinc-455 font-mono uppercase tracking-widest">Expires</span>
                <span className="text-[10px] font-mono font-bold">{cardExpiry}</span>
              </div>
            </div>
          </div>
        </div>

        <div className="flex gap-2">
          <button
            id="btn_swap_payment_card"
            onClick={() => setShowAddCardModal(true)}
            className="w-full py-2 bg-slate-950 dark:bg-slate-800 text-white text-xs font-semibold rounded-lg hover:bg-slate-900 dark:hover:bg-slate-700 transition cursor-pointer flex items-center justify-center gap-1.5"
          >
            <CreditCard className="w-3.5 h-3.5" /> Swap Payment Credentials
          </button>
        </div>
      </div>

      {/* Transaction Webhook logs list */}
      <div className="p-6 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl shadow-xs flex flex-col justify-between space-y-4">
        <div>
          <h3 className="text-xs font-mono font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1.5">
            <Clock className="w-4 h-4 text-blue-500" /> Cashfree Webhooks Audit Log
          </h3>
          <p className="text-[11px] text-slate-500 mt-1 leading-relaxed">
            Autonomous transaction state tracing generated by downstream e-mandate feedback loops.
          </p>
        </div>

        {/* Audit Log timeline list */}
        <div className="flex-grow space-y-3.5 overflow-y-auto max-h-[180px] pr-2 scrollbar-thin">
          {auditLogs.map((log) => (
            <div key={log.id} className="flex gap-2.5 text-xs">
              <span className="font-mono text-[10px] text-slate-450 dark:text-slate-500 w-16 shrink-0 pt-0.5">{log.timestamp}</span>
              <div className="space-y-0.5">
                <span className={`font-semibold text-slate-800 dark:text-slate-250 flex items-center gap-1 ${
                  log.type === 'success' ? 'text-emerald-600 dark:text-emerald-400' : log.type === 'warn' ? 'text-amber-600 dark:text-amber-400' : ''
                }`}>
                  {log.event}
                </span>
                <p className="text-[11px] text-slate-500 dark:text-slate-400 leading-relaxed">{log.details}</p>
              </div>
            </div>
          ))}
        </div>

        <span className="block text-[9.5px] text-slate-400 font-mono border-t border-slate-100 dark:border-slate-800 pt-3">
          Channel Sync Status: <strong className="text-emerald-600 dark:text-emerald-450">● ONLINE / SECURE (TLS 1.3)</strong>
        </span>
      </div>

      {/* Add Card Modal */}
      {showAddCardModal && (
        <div className="fixed inset-0 bg-slate-950/65 backdrop-blur-xs flex items-center justify-center p-4 z-50">
          <div className="w-full max-w-md bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-6 space-y-4 shadow-xl">
            <h3 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-1.5">
              <CreditCard className="w-4.5 h-4.5 text-blue-600" /> Swap Billing Card
            </h3>
            <p className="text-xs text-slate-500">
              Update credit card details used for subsequent recurring Cashfree subscription charges.
            </p>

            <form onSubmit={handleSwapCard} className="space-y-4">
              <div className="space-y-1.5">
                <label className="block text-[10px] font-mono text-slate-450 dark:text-slate-500 uppercase">Card Number</label>
                <input 
                  type="text" 
                  value={inputDigits}
                  onChange={(e) => setInputDigits(e.target.value)}
                  placeholder="4532 7182 9381 2309"
                  className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 text-xs px-3 py-2 rounded-lg font-mono text-slate-900 dark:text-white focus:outline-none"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <label className="block text-[10px] font-mono text-slate-450 dark:text-slate-500 uppercase">Expiry Date</label>
                  <input 
                    type="text" 
                    value={inputExpiry}
                    onChange={(e) => setInputExpiry(e.target.value)}
                    placeholder="12/28"
                    className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 text-xs px-3 py-2 rounded-lg font-mono text-slate-900 dark:text-white focus:outline-none"
                  />
                </div>
                <div className="space-y-1.5">
                  <label className="block text-[10px] font-mono text-slate-450 dark:text-slate-500 uppercase">CVV</label>
                  <input 
                    type="password" 
                    value={inputCvv}
                    onChange={(e) => setInputCvv(e.target.value)}
                    placeholder="***"
                    className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 text-xs px-3 py-2 rounded-lg font-mono text-slate-900 dark:text-white focus:outline-none"
                  />
                </div>
              </div>

              <div className="flex justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setShowAddCardModal(false)}
                  className="px-3.5 py-1.5 text-xs font-semibold text-slate-600 dark:text-slate-450 hover:bg-slate-50 dark:hover:bg-slate-850 border border-slate-250 dark:border-slate-700 rounded-lg cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-3.5 py-1.5 text-xs font-semibold text-white bg-blue-600 hover:bg-blue-700 rounded-lg cursor-pointer"
                >
                  Save Credit Card
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

    </div>
  );
}
